### ISSUE TITLE
Possible issue on session get_bind

### ISSUE THREAD

**Issue by dpgaspar** [pallets-eco/flask-sqlalchemy#953]
This may be a problem on SQLAlchemy itself, simple example:

``` python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///example.sqlite"
db = SQLAlchemy(app)

db.session.get_bind()
```
The output from the execution above:
```
Traceback (most recent call last):
  File "exp.py", line 8, in <module>
    db.session.get_bind()
  File "<string>", line 2, in get_bind
TypeError: get_bind() takes from 1 to 3 positional arguments but 6 were given
```

Should return a SQLAlchemy engine

Environment:

- Python version: 3.7
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.4.7

**Comment by davidism** [comment]
I have absolutely no idea what's going on there, it seems that the frame isn't even available to debug. If you have time, I'd appreciate if you could dig into it, because I won't have time soon.

**Comment by dpgaspar** [comment]
Sure @davidism I'll dig into it. At first it seemed like something was obviously wrong with what I was doing

**Comment by davidism** [comment]
I looked at the code briefly and didn't see anything. Check the sqlalchemy version, might be a compatibility issue?

**Comment by dpgaspar** [comment]
Just a couple of notes:

when using SQLAlchemy < 1.4.0

`return getattr(self.registry(), name)(*args, **kwargs)`

using SQLAlchemy > 1.4.0

```
    @property
    def _proxied(self):
        return self.registry()
```

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/session.py#L4026

Seems that `get_bind()` is called with the session parameters that are 6

**Comment by dpgaspar** [comment]
Leaving an update here:
re-checked this issue with latest SQLAlchemy=1.4.18 and Flask-SQLAlchemy 2.5.1, still an issue different error:

```
    db.session.get_bind()
  File "<string>", line 2, in get_bind
TypeError: get_bind() got an unexpected keyword argument 'bind'
```

**Comment by kanetkarster** [comment]
hi, was just wondering what the next steps are for this? do we need something like 2.5.2 with #955 included in the release?

**Comment by jnahmias** [comment]
Hello,
I understand that this is fixed in master in #943; any update on getting a formal release (whether 2.5.2 or 3.0.0) containing the fix?

**Comment by tachyondecay** [comment]
> Hello, I understand that this is fixed in master in #943; any update on getting a formal release (whether 2.5.2 or 3.0.0) containing the fix?

Please see [this comment](https://github.com/pallets/flask-sqlalchemy/issues/1021#issuecomment-985748363).

**Comment by RomeshA** [comment]
I've been getting a related error with code such as

```python
entries = db.session.execute(s,  bind=db.get_engine(bind="name")).all()
```

which works with sqlalchemy 1.3.24 but fails with sqlalchemy 1.4.31 with

```
TypeError: get_bind() got an unexpected keyword argument 'bind'
```

Unfortunately we rely heavily on pandas and pandas 1.4 raises an error unless sqlalchemy is >=1.4, so simply holding sqlalchemy back is more broadly problematic. However, while waiting for the update to `flask-sqlalchemy` I was able to work around it by substituting the code above with

```python
engine = db.get_engine(bind="name")
session = db.create_scoped_session(options={'bind': engine})
entries = session.execute(s).all()
```

**Comment by davidism** [comment]
fixed in #1087
